export const ENDPOINTS = {
    LOGIN: "auth/login",
    REGISTER: "user/create",
    VERIFY_OTP: "auth/verify",
    UPDATE_USER_DETAILS: "user/update/",
    GET_USER_DETAILS: "user/profile",
    ONBOARDING: "onbording/create",
    GET_ONBOARDING: "onbording/id/",
    UPDATE_ONBOARDING: "onbording/update/",
    AVATAR_LIST: "avatar/list",
    AVATAR_DETAILS:"avatar/id/",
    AVATAR_MESSAGE:"conversation/create/response",
    AVATAR_CREATE:"avatar/create",
    AVATAR_END_SESSION:"avatar/session/close",
    AVATAR_SESSION_CREATE:"avatar/session/create",
    CONVERSATION_SUMMARY:"conversation/summary",
    GET_CONVERSATIONS:"conversation/",
    GET_CONVERSATION_BY_ID:"conversation/id/",
}